/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val nombre: String = "Cruza"
    var fecha = "22/04/25"
    println("¡Hola, Kotlin!")
    println("Me llamo $nombre")
    println("Hoy es $fecha")
}
