/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val nombre: String = "Cruza"
    var fecha = "22/04/25"
    println("¡Hola, Kotlin!")
    println("Me llamo $nombre")
    println("Hoy es $fecha")
    mostrarTiposDeDatos()
}

fun mostrarTiposDeDatos() {
    val nombre: String = "Cruza"
    val edad: Int = 16
    val alturacruza: Double = 1.88
    val esEstudiante: Boolean = true
    
    println("Nombre: $nombre")
    println("Edad: $edad")
    println("Altura: $alturacruza")
    println("Es estudiante: $esEstudiante")

    val base: Double = 5.0
    val altura: Double = 3.0
    val area: Double = base * altura
    println("El área del rectángulo es: $area")
}
